server.port=8080

spring.application.name=task-service

spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Desativa discovery client automático do Spring Cloud pois o Feign conecta direto via URL
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false

# URL do Microsserviço de Notificações para integração distribuída via Spring Cloud Feign
notification.service.url=http://localhost:8082

logging.level.br.com.manoelegidio.tp3=DEBUG
logging.level.org.springframework.cloud.openfeign=DEBUG
