apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secrets
  namespace: taskmanager-prod
  labels:
    app.kubernetes.io/name: taskmanager-system
    app.kubernetes.io/environment: production
type: Opaque
data:
  # Base64 encoded 'guest'
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
  RABBITMQ_USERNAME: Z3Vlc3Q=
  RABBITMQ_PASSWORD: Z3Vlc3Q=
